### ISSUE TITLE
Validation Failed

### ISSUE THREAD

**Issue by jevansfbcmb** [philbertphotos/osticket-alert-plugin#1]
Hi,

When using thus plugin, It does not send an email and this is what is logged in the system log.

Unable to email via SMTP:185.57.153.1:25 [customersupport] Validation failed for: autoconfirm-itsupport@fbcmb.co.uk

Thanks

**Comment by philbertphotos** [comment]
Any error log?

**Comment by philbertphotos** [comment]
Seems like a username or password problem somewhere.

**Comment by jevansfbcmb** [comment]
Hi
That was the only thing that gets added to the log.

**Comment by omarbr** [comment]
Same problem.
Impossibile inviare email via SMTP:mx1.fiaresegroup.it:25 [it-t@fiaresegroup.it] Validation failed for: Support

**Comment by philbertphotos** [comment]
@omarbr this has been all fixed with recent updates.
