### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by MattDecarlo** [philbertphotos/osticket-alert-plugin#2]
Any chance you could help me with this? I don't think this works with the new current version. Got an error about curley brackets. Or if you know how I can prefill a default comment by editing forms class? I found that if we make the agent write a comment when assigning/claiming it will notify the user. Ive set this to require but I can't seem to figure out how to prefill the comment.

**Comment by philbertphotos** [comment]
This plugin works like a charm and feels my need to alert the user as to who is assigned to the ticket in our environment its sorely needed.
I have made several changes and just never updated the github. All should be fine now and it works with all versions.

**Comment by philbertphotos** [comment]
@MattDecarlo  This has all been fixed for OST 1.17+
